version: '2.3'

services:
  redis:
    image: redis:latest
    networks:
      - server_network
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data
volumes:
  redis_data:
networks:
  server_network: